language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode9.1
      compiler: gcc
  allow_failures:
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update;
      sudo apt-get install g++-7 binutils-2.26;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90;
      export PATH=/usr/lib/binutils-2.26/bin:${PATH};
    fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install ccache fontconfig freetype gcc;
      brew link --overwrite gcc;
      export CC=gcc;
      export CXX=g++;
      xcode-select -s /Applications/Xcode.app/Contents/Developer/;
    fi

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - time
    - g++-7
    - gcc-7
    - binutils
    - libc6
    - libc6-amd64
    - libc6-dev
    - libc6-dbg
    - python

env:
  global:
    - MAKEFLAGS="-j2"

before_script:
  - $CC --version
  - ./configure

script:
  - make || (cat vendor/cairo/config.log && exit 1)
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then make test ; fi

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

notifications:
  email: false
