language: cpp
compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode10.1
  allow_failures:
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install g++-7 binutils-2.26 ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90 ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90 ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export PATH=/usr/lib/binutils-2.26/bin:${PATH} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --force-bottle fontconfig freetype; fi

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - time
    - g++-7
    - gcc-7
    - binutils
    - libc6
    - libc6-amd64
    - libc6-dev
    - libc6-dbg
    - python

env:
  global:
    - MAKEFLAGS="-j2"

script:
  - ./configure
  - make
  #- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then make ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make platform=osx -j2 ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then make test ; fi

cache:
    apt: true
    #directories:
    #- vendor

notifications:
  email: false
