# ChaiLove Appveyor Configuration
# https://ci.appveyor.com/project/RobLoach/libretro-chailove
version: '{build}'

platform: x86
configuration: Debug

# Don't build the Documentation
branches:
  except:
    - docs

skip_tags: true
skip_non_tags: false

image: Visual Studio 2017

environment:
  CC: gcc.exe
  TARGET: cairo_libretro.dll
  platform: win
  system_platform: win

init:
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive
  - C:\MinGW\bin\mingw-get install autotools autoconf automake
  - copy c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\mingw32-make.exe c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\make.exe
  - cmd: set PATH=%PATH%;c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  - path

before_build:
  - make --version
  - gcc --version

build_script:
  - make

# TODO: Add automated testing
#before_test:
#  - make vendor/noarch/noarch
#
#test_script:
#  - make unittest

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    #- platform: x64
    #  configuration: Release
