# libretro-cairo
SOURCES_CXX := $(wildcard \
	$(CORE_DIR)/src/*.cpp \
)

# libretro-common
FLAGS += -I$(CORE_DIR)/vendor/libretro-common/include \
    -I$(CORE_DIR)/tmp/include

ifneq (,$(findstring msvc2003,$(platform)))
INCFLAGS += -I$(CORE_DIR)/vendor/libretro-common/include/compat/msvc
endif

# libretro-common audio
SOURCES_C += $(CORE_DIR)/vendor/libretro-common/audio/audio_mixer.c \
	$(CORE_DIR)/vendor/libretro-common/formats/wav/rwav.c \
	$(CORE_DIR)/vendor/libretro-common/memmap/memalign.c \
    $(CORE_DIR)/vendor/libretro-common/audio/resampler/audio_resampler.c \
    $(CORE_DIR)/vendor/libretro-common/audio/resampler/drivers/sinc_resampler.c \
    $(CORE_DIR)/vendor/libretro-common/audio/resampler/drivers/nearest_resampler.c \
    $(CORE_DIR)/vendor/libretro-common/audio/resampler/drivers/null_resampler.c \
    $(CORE_DIR)/vendor/libretro-common/features/features_cpu.c \
    $(CORE_DIR)/vendor/libretro-common/compat/compat_strl.c \
    $(CORE_DIR)/vendor/libretro-common/file/config_file_userdata.c \
    $(CORE_DIR)/vendor/libretro-common/file/file_path.c \
    $(CORE_DIR)/vendor/libretro-common/file/config_file.c \
    $(CORE_DIR)/vendor/libretro-common/streams/file_stream.c \
    $(CORE_DIR)/vendor/libretro-common/vfs/vfs_implementation.c \
    $(CORE_DIR)/vendor/libretro-common/compat/compat_strcasestr.c \
    $(CORE_DIR)/vendor/libretro-common/lists/string_list.c

OBJECTS += $(SOURCES_CXX:.cpp=.o) $(SOURCES_C:.c=.o)

LDFLAGS +=  $(fpic) $(SHARED) $(EXTRA_LDF)

WARNINGS :=
